dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    serialization: fastjson
    name: dubbo
  registry:
    address: nacos://${goldhorse.nacos.host}:${goldhorse.nacos.port}
    group: ${goldhorse.nacos.group}
    parameters[namespace]: ${goldhorse.nacos.namespace}
    protocol: dubbo
    #metadata-report:
    #address: nacos://${goldhorse.nacos.host}:${goldhorse.nacos.port}
    #group: ${goldhorse.nacos.group}
    #parameters[namespace]: ${goldhorse.nacos.namespace}
  scan:
    base-packages: hk.com.easyview
  provider:
    timeout: 3000
    delay: 1
    retries: 0
  consumer:
    timeout: 3000
spring:
  datasource:
    url: jdbc:mysql://${goldhorse.mysql.host}:${goldhorse.mysql.port}/${goldhorse.mysql.database}?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${goldhorse.mysql.username}
    password: ${goldhorse.mysql.password}
    tomcat:
      initial-size: ${goldhorse.mysql.connectInitialSize}
      min-idle: ${goldhorse.mysql.connectInitialSize}
  redis:
    database: ${goldhorse.redis.database}
    host: ${goldhorse.redis.host}
    port: ${goldhorse.redis.port}
    password: ${goldhorse.redis.password}
    timeout: 3000
    jedis:
      pool:
        max-active: 20
        max-wait: 20
        max-idle: 10
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${goldhorse.nacos.host}:${goldhorse.nacos.port}
        group: ${goldhorse.nacos.group}
        namespace: ${goldhorse.nacos.namespace}

nacos:
  config:
    server-addr: ${goldhorse.nacos.host}:${goldhorse.nacos.port}
    group: ${goldhorse.nacos.group}
    namespace: ${goldhorse.nacos.namespace}
    time-out: 5000


logging:
  config: classpath:logback-${goldhorse.env}.xml
  level:
    root: WARN
    org:
      apache:
        dubbo: INFO
    hk:
      com:
        easyview: ${goldhorse.log.level}

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  tomcat:
    basedir: /app/backend/goldhorse/tmp/tomcat/

