goldhorse:
  env: prod
  nacos:
    host: 172.19.0.39
    port: 8848
    group: goldhorse
    namespace: 5e0a1115-131b-40d8-bc54-89e3b33eafc4
  mysql:
    host: 172.19.0.46
    port: 3306
    database: goldhorse
    username: goldhorse
    password: goldhorse-(2020)
    connectInitialSize: 10
  redis:
    database: 1
    host: 172.19.0.22
    port: 6379
    password: '!EV@{trs}!'
  log:
    level: DEBUG
  sso:
    passwordVerifyNum: 3
    passwordVerifyTimeout: 5
    loginFailNum: 3
    loginFailNumFrozen: 20
    commonEquipmentLoginNum: 3
    uncommonEquipmentLoginNum: 3
    tokenExpireMinute: 720
    tradeTokenExpireMinute: 180
    mobileTokenExpireMinute: 518400
    frozenSsoKey: goldhorse:account:frozen
    frozenExpireMinute: 60
  report:
    kafka:
      bootstrap-servers: 172.19.0.30:9092,172.19.0.39:9092
  appVersion:
    openCheck: false
    version: 1.6.1
    downloadAddress:
  systemStable:
    unavailable: false
    whiteList: loginName1,loginName2
    distributing: false
    remindWarn: false
    terminalTypes: Web_distribution,Web_Extramile
  quotationTrade:
    miniProgramAccounts: 10000000191,20078000002
spring:
  profiles:
    include: common